# Site settings
title: OpenGL Superbook Dojo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/opengl-sb6-samples" # the subpath of your site, e.g. /blog/
url: "wakita.github.io"

owner:
  name: Ken Wakita
  email: ken_wakita@me.com
  facebook: k.wakita
  twitter_username: kwakita
  github_username:  wakita
encoding: utf-8


# Build settings
github: [Repository metadata]
pygments: true
timezone: Japan/Tokyo
markdown: kramdown
paginate: 5
